[package]
name = "news-api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = { version = "1.39.2", features = ["full"] }
